<?php

use Illuminate\Database\Seeder;

class DepartmentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('departments')->delete();
        
        \DB::table('departments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Directors',
                'name_kh' => 'ថ្នាក់ដឹកនាំ',
                'abr' => 'Director',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:35:56',
                'updated_at' => '2018-12-11 09:35:56',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Chirurgie A',
                'name_kh' => 'ផ្នែកសល្យសាស្ត្រ "ក"',
                'abr' => 'CHA',
                'abr_kh' => NULL,
                'beds' => 86,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:39:34',
                'updated_at' => '2019-01-21 14:14:22',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Reanimation A',
                'name_kh' => 'ផ្នែកប្រពោធនកម្ម "ក"',
                'abr' => 'RA',
                'abr_kh' => NULL,
                'beds' => 14,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:40:17',
                'updated_at' => '2019-01-21 14:14:38',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Reanimation B',
                'name_kh' => 'ផ្នែកប្រពោធនកម្ម ខ',
                'abr' => 'RB',
                'abr_kh' => NULL,
                'beds' => 20,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:41:18',
                'updated_at' => '2019-01-21 14:14:51',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Maternite',
                'name_kh' => 'ផ្នែកសម្ភព',
                'abr' => 'MT',
                'abr_kh' => NULL,
                'beds' => 170,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:42:06',
                'updated_at' => '2018-12-11 09:42:06',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Anesthesie-Reveil',
                'name_kh' => 'ផ្នែកសណ្តំ និងភ្ញាក់ពីសណ្តំ',
                'abr' => 'AR',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:43:24',
                'updated_at' => '2019-04-09 21:24:33',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Gynecology',
                'name_kh' => 'ផ្នែករោគស្រ្តី',
                'abr' => 'GO',
                'abr_kh' => NULL,
                'beds' => 20,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:44:16',
                'updated_at' => '2018-12-11 09:44:16',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Medecine A',
                'name_kh' => 'ផ្នែកជំងឺទូទៅ ក',
                'abr' => 'MA',
                'abr_kh' => NULL,
                'beds' => 52,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:45:25',
                'updated_at' => '2019-01-21 14:16:02',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Medecine B',
                'name_kh' => 'ផ្នែកជំងឺទូទៅ ខ',
                'abr' => 'MB',
                'abr_kh' => NULL,
                'beds' => 55,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:46:07',
                'updated_at' => '2019-01-21 14:16:37',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Medecine A4',
                'name_kh' => 'ផ្នែកជំងឺទូទៅ ក៤',
                'abr' => 'MA4',
                'abr_kh' => NULL,
                'beds' => 64,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:48:28',
                'updated_at' => '2019-01-21 14:17:16',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Onco Hematolgie',
                'name_kh' => 'ផ្នែកមហារីក និងជំងឺឈាម',
                'abr' => 'Onco',
                'abr_kh' => NULL,
                'beds' => 55,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:50:01',
                'updated_at' => '2019-01-21 14:17:49',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Urgences Port',
                'name_kh' => 'ផ្នែកសង្គ្រោះបន្ទាន់',
                'abr' => 'UP',
                'abr_kh' => NULL,
                'beds' => 20,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:52:15',
                'updated_at' => '2019-01-21 14:14:06',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Chirurgie B',
                'name_kh' => 'ផ្នែកសល្យសាស្ត្រ​ "ខ"',
                'abr' => 'CHB',
                'abr_kh' => NULL,
                'beds' => 40,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:54:31',
                'updated_at' => '2018-12-11 09:54:31',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Hémodialyse',
                'name_kh' => 'មជ្ឈមណ្ឌលលាងឈាម ជាស៊ីម',
                'abr' => 'HD',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:57:00',
                'updated_at' => '2019-01-21 14:18:35',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Hépato Gastro Entérologie',
                'name_kh' => 'អ៊ុយនីតេ ថ្លើម ក្រពះ ពោះវៀន',
                'abr' => 'HG',
                'abr_kh' => NULL,
                'beds' => 17,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 09:58:33',
                'updated_at' => '2019-01-21 14:18:53',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Réa Neuro',
                'name_kh' => 'ផ្នែកប្រពោធនកម្មប្រព័ន្ធប្រសាទ',
                'abr' => 'RN',
                'abr_kh' => NULL,
                'beds' => 16,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:00:00',
                'updated_at' => '2019-01-21 14:19:07',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Neuro Chirurgie',
                'name_kh' => 'អ៊ុយនីតេ វះកាត់ប្រព័ន្ធប្រសាទ',
                'abr' => 'CHN',
                'abr_kh' => NULL,
                'beds' => 43,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:00:39',
                'updated_at' => '2019-01-21 14:19:32',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Consultation Externe',
                'name_kh' => 'អ៊ុយនីតេ ពិគ្រោះជំងឺក្រៅ',
                'abr' => 'CE',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:02:45',
                'updated_at' => '2018-12-11 10:02:45',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'O.R.L',
                'name_kh' => 'ផ្នែកត្រចៀក ច្រមុះ បំពង់ក',
                'abr' => 'ORL',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:06:20',
                'updated_at' => '2018-12-11 10:06:20',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Ophtalmologie',
                'name_kh' => 'អ៊ុយនីតេ ចក្ខុរោគ',
                'abr' => 'Oph',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:07:20',
                'updated_at' => '2018-12-11 10:07:20',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Imagerie Médicale',
                'name_kh' => 'ផ្នែករូបភាពវេជ្ជសាស្ត្រ',
                'abr' => 'IM',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:08:05',
                'updated_at' => '2018-12-11 10:08:05',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Laboratoire',
                'name_kh' => 'ផ្នែកមន្ទីរពិសោធន៍',
                'abr' => 'Labo',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:08:37',
                'updated_at' => '2018-12-11 10:08:37',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Pharmacie',
                'name_kh' => 'ផ្នែកឱសថស្ថាន',
                'abr' => 'PH',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:09:17',
                'updated_at' => '2018-12-11 10:09:17',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Kiné Therapie',
                'name_kh' => 'ផ្នែកព្យាបាលដោយចលនា',
                'abr' => 'Kiné',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:10:24',
                'updated_at' => '2018-12-11 10:10:24',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Bloc Opératoire',
                'name_kh' => 'ផ្នែកសល្យាគារ',
                'abr' => 'BO',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:11:26',
                'updated_at' => '2018-12-11 10:11:26',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'SAMU',
                'name_kh' => 'ផ្នែកសាមុយ',
                'abr' => 'SAMU',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:11:59',
                'updated_at' => '2018-12-11 10:11:59',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Electronique Micale',
                'name_kh' => 'ផ្នែកបច្ចេកទេសអេឡិចត្រូនិច',
                'abr' => 'EM',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:13:45',
                'updated_at' => '2018-12-11 10:13:45',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Travail Général',
                'name_kh' => 'ផ្នែកការងារទូទៅ',
                'abr' => 'TG',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:14:49',
                'updated_at' => '2018-12-11 10:14:49',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Néonatologie',
                'name_kh' => 'អ៊ុយនីតេ ប្រពោធនកម្មទារក',
                'abr' => 'Néo',
                'abr_kh' => NULL,
                'beds' => 18,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:15:41',
                'updated_at' => '2018-12-11 10:15:41',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
            'name' => 'CCPP (CE)',
            'name_kh' => 'ដេប៉ាតឺម៉ង់មជ្ឈមណ្ឌលព្យាបាលជំងឺបេះដូង(ពិគ្រោះជំងឺក្រៅ)',
            'abr' => 'CCPP (CE)',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:17:35',
                'updated_at' => '2019-01-21 14:20:51',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Neurologie',
                'name_kh' => 'អ៊ុយនីតេប្រសាទសាស្រ្ត',
                'abr' => 'Neuro',
                'abr_kh' => NULL,
                'beds' => 35,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:18:28',
                'updated_at' => '2018-12-11 10:18:28',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Bureau du Comptabilité',
                'name_kh' => 'ការិយាល័យគណនេយ្យ',
                'abr' => 'BC',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:20:16',
                'updated_at' => '2018-12-11 10:20:16',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Bureau d\'Administration',
                'name_kh' => 'ការិយាល័យរដ្ឋបាល',
                'abr' => 'BA',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:20:52',
                'updated_at' => '2018-12-11 10:20:52',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Bureau Technique',
                'name_kh' => 'ការិយាល័យបច្ចេកទេស',
                'abr' => 'BT',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:21:37',
                'updated_at' => '2018-12-11 10:21:37',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'SIM',
            'name_kh' => 'ការិយាល័យបច្ចេកទេស (ព័ត៌មានសុខាភិបាល)',
                'abr' => 'SIM',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:22:35',
                'updated_at' => '2018-12-11 10:22:35',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
            'name' => 'Bloc Operatoire (CCPP)',
            'name_kh' => 'សល្យាគារ (ដេប៉ាតឺម៉ង់មជ្ឈមណ្ឌលព្យាបាលជំងឺបេះដូង)',
            'abr' => 'BO (CCPP)',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:23:44',
                'updated_at' => '2018-12-11 10:23:44',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
            'name' => 'Angio (CCPP)',
            'name_kh' => 'ឆ្លុះសរសៃឈាមបេះដូង (ដេប៉ាតឺម៉ង់មជ្ឈមណ្ឌលព្យាបាលជំងឺបេះដូង)',
                'abr' => 'Angio',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:24:46',
                'updated_at' => '2018-12-11 10:24:46',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
            'name' => 'PVE (CCPP)',
            'name_kh' => 'បេះដូងកុមារ (ដេប៉ាតឺម៉ង់មជ្ឈមណ្ឌលព្យាបាលជំងឺបេះដូង)',
                'abr' => 'PVE',
                'abr_kh' => NULL,
                'beds' => 10,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:25:44',
                'updated_at' => '2019-01-21 14:21:28',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
            'name' => 'Cardio A (CCPP)',
            'name_kh' => 'ជំងឺបេះដូង ក (ដេប៉ាតឺម៉ង់មជ្ឈមណ្ឌលព្យាបាលជំងឺបេះដូង)',
                'abr' => 'Cardio A',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:27:09',
                'updated_at' => '2018-12-11 10:27:09',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
            'name' => 'Cardio B (CCPP)',
            'name_kh' => 'ជំងឺបេះដូង ខ (ដេប៉ាតឺម៉ង់មជ្ឈមណ្ឌលព្យាបាលជំងឺបេះដូង)',
                'abr' => 'Cardio B',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:28:00',
                'updated_at' => '2018-12-11 10:28:00',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'CCPP',
                'name_kh' => 'ដេប៉ាតឺម៉ង់មជ្ឈមណ្ឌលព្យាបាលជំងឺបេះដូង',
                'abr' => 'CCPP',
                'abr_kh' => NULL,
                'beds' => 45,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:28:50',
                'updated_at' => '2019-01-21 14:21:09',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
            'name' => 'Reanimation (CCPP)',
            'name_kh' => 'ប្រពោធនកម្មបេះដូង (ដេប៉ាតឺម៉ង់មជ្ឈមណ្ឌលព្យាបាលជំងឺបេះដូង)',
                'abr' => 'Réa CCPP',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-11 10:29:39',
                'updated_at' => '2018-12-11 10:29:39',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 44,
                'name' => 'Medecine A5',
                'name_kh' => 'ជំងឺទូទៅ ក៥',
                'abr' => 'Med A5',
                'abr_kh' => NULL,
                'beds' => 20,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2018-12-21 03:14:28',
                'updated_at' => '2018-12-21 03:14:28',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 45,
                'name' => 'Chirurgie A2',
                'name_kh' => 'ផ្នែកសល្យសាស្ត្រ ក២',
                'abr' => 'Chir A2',
                'abr_kh' => NULL,
                'beds' => 64,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2019-03-05 08:34:07',
                'updated_at' => '2019-03-05 08:34:07',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 46,
                'name' => 'Rea Cardio',
                'name_kh' => 'ប្រពោធនកម្មបេះដូង',
                'abr' => 'Rea CCPP',
                'abr_kh' => NULL,
                'beds' => 12,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2019-03-05 08:43:22',
                'updated_at' => '2019-03-05 08:43:22',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 47,
                'name' => 'Bloc Opératoire New Maternité',
                'name_kh' => 'សល្យាគារ សម្ភពថ្មី',
                'abr' => 'Bloc Mat',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2019-03-29 21:44:34',
                'updated_at' => '2019-03-29 21:44:34',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 48,
                'name' => 'Bloc Opératoire Neuroscience',
                'name_kh' => 'សល្យាគារ មជ្ឈមណ្ឌលវិទ្យាសាស្ត្រប្រព័ន្ធប្រសាទ',
                'abr' => 'Bloc NS',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2019-03-29 21:45:29',
                'updated_at' => '2019-03-29 21:45:29',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 49,
                'name' => 'Reanimation Chirurgie Cardio',
                'name_kh' => 'ប្រពោធនកម្មវះកាត់បេះដូង',
                'abr' => 'Rea Chir Cardio',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2019-03-31 20:15:48',
                'updated_at' => '2019-03-31 20:15:48',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 50,
                'name' => 'Bloc opératoir cardio',
                'name_kh' => 'សល្យាគារបេះដូង',
                'abr' => 'Bloc Cardio',
                'abr_kh' => 'សល្យាគារបេះដូង',
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2019-04-02 21:42:13',
                'updated_at' => '2019-05-06 18:36:55',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 51,
                'name' => 'Anesthesie-Reveil Maternité',
                'name_kh' => 'ផ្នែកសណ្តំ និងភ្ញាក់ពីសណ្តំ សម្ភពសន្តិភាព',
                'abr' => 'Reveil Mat',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2019-04-09 21:18:33',
                'updated_at' => '2019-04-09 21:23:57',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 52,
                'name' => 'Anesthesie-Reveil Neuroscience',
                'name_kh' => 'ផ្នែកសណ្តំ និងភ្ញាក់ពីសណ្តំ មជ្ឈមណ្ឌលវិទ្យាសាស្ត្រប្រព័ន្ធប្រសាទ',
                'abr' => 'Reveil NS',
                'abr_kh' => NULL,
                'beds' => NULL,
                'description' => NULL,
                'active' => 1,
                'created_at' => '2019-04-09 21:19:21',
                'updated_at' => '2019-04-09 21:24:21',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}